# Generated by Django 4.2.6 on 2023-10-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('imei1', models.IntegerField()),
                ('imei2', models.IntegerField()),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('yes', 'Qeydiyyatdan keçib'), ('no', 'Qeydiyyatdan keçməyib')], max_length=50)),
            ],
        ),
    ]
