# Generated by Django 4.2.6 on 2023-10-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_phones_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phones',
            old_name='imei1',
            new_name='imei',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='imei2',
        ),
    ]
