# Generated by Django 4.2.6 on 2023-10-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_phones_activation_date_phones_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='activation_date',
        ),
    ]
