# Generated by Django 4.2.6 on 2023-10-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_phones_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
