# Generated by Django 4.2.6 on 2023-10-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_phones_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='status',
            field=models.CharField(default='Qedyiyyatdan keçirilməyib!', max_length=100),
        ),
    ]
